# Generated by Django 3.1.3 on 2020-12-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('Bus_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Capacity', models.IntegerField(max_length=3)),
                ('Bus_Driver_Id', models.CharField(max_length=15, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bus_Driver',
            fields=[
                ('Bus_Driver_Id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=25, null=True)),
                ('Lname', models.CharField(max_length=25, null=True)),
                ('Email', models.CharField(max_length=50, null=True)),
                ('Contact_Number', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('Location_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Location_Name', models.CharField(max_length=50, null=True)),
                ('Latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('Longtitude', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
        ),
    ]
