# Generated by Django 3.1.3 on 2020-12-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_auto_20201216_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_driver_route',
            name='Departure_Time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='From_Location_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='Time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='To_Location_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='route_location',
            name='Estimated_Time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='route_location',
            name='Location_Order',
            field=models.IntegerField(null=True),
        ),
    ]
