# Generated by Django 3.1.3 on 2020-12-16 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_auto_20201216_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_driver_route',
            name='Route_Id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admins.route'),
        ),
        migrations.AddField(
            model_name='route_location',
            name='Location_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='admins.location'),
        ),
        migrations.AddField(
            model_name='route_location',
            name='Route_Id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='admins.route'),
        ),
        migrations.AlterField(
            model_name='bus_driver_route',
            name='Bus_Driver_Id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admins.bus_driver'),
        ),
    ]
