# Generated by Django 3.1.3 on 2020-12-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_auto_20201216_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='route',
            new_name='Route_Id',
        ),
    ]
