# Generated by Django 3.1.3 on 2020-12-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_auto_20201216_1611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bus_Driver',
            new_name='Bus_Drivers',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='Staff_Id',
            new_name='Staff_id',
        ),
        migrations.RenameField(
            model_name='bus_driver_route',
            old_name='Bus_Driver_Id',
            new_name='Bus_Driver',
        ),
        migrations.RenameField(
            model_name='bus_driver_route',
            old_name='Route_id',
            new_name='Route',
        ),
        migrations.RenameField(
            model_name='bus_drivers',
            old_name='Bus_Driver_Id',
            new_name='Bus_Driver_id',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='Reservation_Id',
            new_name='Reservation_id',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='Route_Id',
            new_name='Route',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='Student_Id',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='Route_Id',
            new_name='Route_id',
        ),
        migrations.RenameField(
            model_name='route_location',
            old_name='Location_id',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='route_location',
            old_name='Route_Id',
            new_name='Route',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Student_Id',
            new_name='Student_id',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='Bus_Driver_Id',
        ),
    ]
