# Generated by Django 3.1.3 on 2020-12-16 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_auto_20201216_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='Bus_Driver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admins.bus_drivers'),
        ),
    ]
