# Generated by Django 3.1.3 on 2020-12-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_bus_bus_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus_driver_route',
            name='id',
        ),
        migrations.RemoveField(
            model_name='route_location',
            name='id',
        ),
        migrations.AddField(
            model_name='bus_driver_route',
            name='Bus_Driver_Route_id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='route_location',
            name='Route_Location_id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
    ]
