# Generated by Django 3.1.3 on 2020-12-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_auto_20201223_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='Time',
            new_name='Arrival_Time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='Departure_Time',
            field=models.TimeField(null=True),
        ),
    ]
