# Generated by Django 3.1.3 on 2020-12-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0011_bus_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Bus_Driver_Route_id',
            field=models.IntegerField(null=True),
        ),
    ]
