# Generated by Django 3.1.3 on 2020-12-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0012_reservation_bus_driver_route_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_drivers',
            name='Bus_Driver_id',
            field=models.AutoField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
