# Generated by Django 3.1.3 on 2020-12-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0013_auto_20201225_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_drivers',
            name='Bus_Driver_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
