# Generated by Django 3.1.3 on 2020-12-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0015_auto_20201226_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='Bus_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
