# Generated by Django 3.1.3 on 2020-12-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0016_auto_20201226_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='Route_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
