# Generated by Django 3.1.3 on 2020-12-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0017_auto_20201228_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_driver_route',
            name='Arrival_time',
            field=models.TimeField(null=True),
        ),
    ]
