# Generated by Django 3.1.3 on 2021-01-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0018_bus_driver_route_arrival_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus_driver_route',
            name='Arrival_time',
        ),
        migrations.AddField(
            model_name='bus_driver_route',
            name='Status',
            field=models.IntegerField(default=0),
        ),
    ]
