# Generated by Django 3.1.3 on 2021-01-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0021_auto_20210105_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='Email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
