# Generated by Django 3.1.3 on 2021-01-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0022_auto_20210105_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='Staff_id',
            new_name='username',
        ),
    ]
