# Generated by Django 3.1.3 on 2021-01-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0023_auto_20210109_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_drivers',
            name='Bus_Driver_id',
            field=models.AutoField(default=1000, primary_key=True, serialize=False),
        ),
    ]
