# Generated by Django 3.1.3 on 2021-01-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0024_auto_20210114_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_drivers',
            name='Bus_Driver_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
