# Generated by Django 3.1.3 on 2021-01-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0025_auto_20210114_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='Bus_id',
            field=models.CharField(default=1000, max_length=10, primary_key=True, serialize=False),
        ),
    ]
