# Generated by Django 3.1.3 on 2021-01-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0027_auto_20210114_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='Location_id',
            field=models.AutoField(default=1000, primary_key=True, serialize=False),
        ),
    ]
