# Generated by Django 3.1.3 on 2021-01-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0029_auto_20210114_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_driver_route',
            name='Bus_Driver_Route_id',
            field=models.AutoField(default=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='Route_id',
            field=models.AutoField(default=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='route_location',
            name='Route_Location_id',
            field=models.AutoField(default=1000, primary_key=True, serialize=False),
        ),
    ]
