# Generated by Django 3.1.3 on 2021-01-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0031_auto_20210114_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route_location',
            name='Route_Location_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
