# Generated by Django 3.1.3 on 2021-01-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0032_auto_20210114_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_driver_route',
            name='Status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
