# Generated by Django 3.1.3 on 2021-01-14 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0033_auto_20210114_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route_location',
            name='Route',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admins.route'),
        ),
    ]
