# Generated by Django 3.1.3 on 2021-01-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0034_auto_20210114_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_driver_route',
            name='Status',
            field=models.IntegerField(null=True),
        ),
    ]
