# Generated by Django 3.1.3 on 2021-01-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0035_auto_20210114_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_driver_route',
            name='Bus_Driver_Route_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
