# Generated by Django 3.1.3 on 2021-01-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0037_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route_location',
            name='Estimated_Time',
            field=models.DurationField(null=True),
        ),
    ]
