# Generated by Django 3.1.3 on 2021-01-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0038_auto_20210118_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route_location',
            name='Estimated_Time',
            field=models.TimeField(null=True),
        ),
    ]
