# Generated by Django 3.1.3 on 2021-01-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0040_auto_20210119_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
