# Generated by Django 3.1.3 on 2021-01-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0041_auto_20210120_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Reservation_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
