# Generated by Django 3.1.3 on 2021-01-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0042_auto_20210120_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_drivers',
            name='Fname',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='bus_drivers',
            name='Lname',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
